export const ADD_BILL = 'ADD_BILL';
export const DELETE_BILL = 'DELETE_BILL';
export const MODIFY_BILL = 'MODIFY_BILL';

export const ADD_PARENT_ACCOUNT = 'ADD_PARENT_ACCOUNT';
export const DELETE_PARENT_ACCOUNT = 'DELETE_PARENT_ACCOUNT';
export const MODIFY_PARENT_ACCOUNT = 'MODIFY_PARENT_ACCOUNT';

export const UPDATE_INCOME = 'UPDATE_INCOME';
